# Copyright 2025 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - errorlint
    - exhaustive
    - gocritic
    - godot
    - gosec
    - misspell
    - modernize
    - nilerr
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - exitAfterDefer
        - unnamedResult
    gosec:
      excludes:
        - G101
        - G107
        - G110
        - G115
        - G204
        - G301
        - G302
        - G304
        - G306
    revive:
      rules:
        - name: exported
          disabled: false
formatters:
  enable:
    - gofmt
    - goimports
